spring:
  application:
    name: book-service
server:
  port: 8081

eureka:
  client:
    healthcheck:
      enabled: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1